# Generated by Django 5.2.16 on 2026-08-03 06:16

import accounts.managers
from django.db import migrations, models


def purge_soft_deleted_and_legacy_activity(apps, schema_editor):
    """Permanently remove soft-deleted students and login/noise activity rows.

    Soft deletion and per-login activity logging are being removed in this
    migration, so any previously recorded DELETED accounts and LOGIN / LOGOUT /
    OTP / PASSWORD_CHANGED activity rows are cleaned up here.
    """
    User = apps.get_model("accounts", "User")
    UserActivity = apps.get_model("accounts", "UserActivity")
    User.objects.filter(status="DELETED").delete()
    legacy_actions = ["LOGIN", "LOGOUT", "PASSWORD_CHANGED", "OTP_SENT", "OTP_VERIFIED"]
    UserActivity.objects.filter(action__in=legacy_actions).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # The purge of soft-deleted users leaves pending deferred trigger events on
    # the self-referential `deleted_by` FK; those must be committed before the
    # same table can be ALTERed, so run each operation in its own transaction.
    atomic = False

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(purge_soft_deleted_and_legacy_activity, noop),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('classic_white', 'Classic White'), ('midnight_black', 'Midnight Black'), ('ocean_blue', 'Ocean Blue'), ('emerald_green', 'Emerald Green'), ('royal_purple', 'Royal Purple'), ('sunset_orange', 'Sunset Orange'), ('rose_pink', 'Rose Pink'), ('slate_gray', 'Slate Gray'), ('cyber_neon', 'Cyber Neon'), ('coffee_brown', 'Coffee Brown')], default='classic_white', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('PROFILE_UPDATED', 'Profile Updated'), ('ACCOUNT_BLOCKED', 'Account Blocked'), ('ACCOUNT_UNBLOCKED', 'Account Unblocked'), ('ACCOUNT_DELETED', 'Account Deleted')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'last_login'], name='accounts_us_role_16db87_idx'),
        ),
    ]
