# Generated by Django 5.2.16 on 2026-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
