# Generated by Django 5.2.16 on 2026-08-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_reseed_face_avatars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optional custom photo. Rendered in place of the curated avatar.', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('classic_white', 'Classic White'), ('midnight_black', 'Midnight Black'), ('ocean_blue', 'Ocean Blue'), ('emerald_green', 'Emerald Green'), ('royal_purple', 'Royal Purple'), ('sunset_orange', 'Sunset Orange'), ('rose_pink', 'Rose Pink'), ('slate_gray', 'Slate Gray'), ('cyber_neon', 'Cyber Neon'), ('coffee_brown', 'Coffee Brown'), ('navy_dark', 'Navy Dark'), ('forest_teal', 'Forest Teal'), ('crimson_red', 'Crimson Red'), ('lavender_light', 'Lavender'), ('mint_light', 'Mint')], default='classic_white', max_length=30),
        ),
    ]
