# Generated by Django 5.2.16 on 2026-08-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_avatar_library_static_pngs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='icon_path',
            field=models.TextField(blank=True, help_text='Inline SVG portrait markup (viewBox 0 0 96 96).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Custom profile photo (admins). Rendered in place of the avatar.', null=True, upload_to='avatars/'),
        ),
    ]
