# Generated by Django 5.2.16 on 2026-08-03 08:41

from django.db import migrations, models


def backfill_names(apps, schema_editor):
    Avatar = apps.get_model("accounts", "Avatar")
    for avatar in Avatar.objects.all():
        if avatar.name:
            continue
        if avatar.gender == "female":
            avatar.name = f"Professional Woman {avatar.display_order}"
        else:
            avatar.name = f"Professional Man {avatar.display_order - 10}"
        avatar.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional uploaded image. When set, it is used instead of the static illustration.', null=True, upload_to='avatars/library/'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='name',
            field=models.CharField(blank=True, help_text='Display name, e.g. "Professional Woman 1".', max_length=60),
        ),
        migrations.RunPython(backfill_names, migrations.RunPython.noop),
    ]
