# Generated by Django 5.2.7 on 2026-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_avatar_crud_name_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Custom profile photo (admins). Rendered in place of the avatar.', max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
