# Generated by Django 5.2.16 on 2026-08-03 06:16

import django.db.models.deletion
from django.db import migrations, models


def convert_archived_to_inactive(apps, schema_editor):
    """Map archived (soft-deleted) semesters to INACTIVE before removing the
    ARCHIVED status."""
    Semester = apps.get_model("academics", "Semester")
    Semester.objects.filter(status="ARCHIVED").update(status="INACTIVE")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_archived_to_inactive, noop),
        migrations.AlterModelManagers(
            name='semester',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='semester',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='archived_by',
        ),
        migrations.AddField(
            model_name='semester',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='semesters/'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='subjects/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.semester')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['semester', 'status'], name='academics_s_semeste_244267_idx')],
            },
        ),
    ]
