# Generated by Django 5.2.7 on 2026-08-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_semester_managers_remove_semester_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('chapter_number', models.PositiveIntegerField(default=1, help_text='Chapter number or module index')),
                ('pdf_url', models.URLField(blank=True, help_text='Direct URL to PDF (Supabase, Drive, CDN)', max_length=500)),
                ('pdf_file', models.FileField(blank=True, help_text='Upload local PDF file', null=True, upload_to='chapters/pdfs/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.subject')),
            ],
            options={
                'ordering': ['display_order', 'chapter_number', 'id'],
                'indexes': [models.Index(fields=['subject', 'status'], name='academics_c_subject_716f97_idx')],
            },
        ),
    ]
