# Generated by Django 5.2.7 on 2026-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='subname',
            field=models.CharField(blank=True, help_text='Subname or subtitle (e.g. Unit 1 / Topic)', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(help_text='Chapter name / main title', max_length=150),
        ),
    ]
