# Generated by Django 5.2.7 on 2026-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_chapter_subname_alter_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English Notes'), ('MALAYALAM', 'Malayalam Notes')], default='ENGLISH', help_text='Language medium of this chapter (English or Malayalam)', max_length=15),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject', 'language', 'status'], name='academics_c_subject_7d139a_idx'),
        ),
    ]
