# Generated by Django 5.2.7 on 2026-08-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_chapter_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='semesters/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='subjects/'),
        ),
    ]
