# Generated by Django 5.2.7 on 2026-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_semester_thumbnail_alter_subject_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='kind',
            field=models.CharField(choices=[('MODULE', 'Module'), ('CHAPTER', 'Chapter')], default='MODULE', help_text='Whether this entry is a Module or a Chapter.', max_length=10),
        ),
    ]
