# Generated by Django 5.2.7 on 2026-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_chapter_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='chapters/thumbnails/'),
        ),
    ]
