# Generated by Django 5.2.16 on 2026-08-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_chapter_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='medium',
            field=models.CharField(choices=[('BOTH', 'English & Malayalam'), ('ENGLISH_ONLY', 'English only'), ('MALAYALAM_ONLY', 'Malayalam only')], default='BOTH', help_text='Which language medium this subject offers.', max_length=20),
        ),
    ]
