# Generated by Django 5.2.7 on 2026-08-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitypost',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='communitypost',
            name='parent_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_to', to='community.communitypost'),
        ),
    ]
